spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # DB ??
  datasource:
    # ??? H2 DB? ?? URL
    url: jdbc:h2:mem:db;NON_KEYWORDS=USER
    # ??? ?? ????
    driver-class-name: org.h2.Driver
    # springboot 2.4 ??? username? ? ??????. ??? ??? ?????.
    username: sa
    password:

  security:
    user:
      name: username
      password: password

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  jpa:
    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug